#
# Copyright 2019 is-land
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# this compose file is used to build ohara's images.
# You can build all images by command "docker-compose -f ./build.yml build --parallel"
# and then push them to docker hub by command "docker-compose -f ./build.yml push"
# NOTED: you can export a variable "TAG" to change tag of image. For example, export TAG=123 and build this file. All output will be tagged with "123"
version: '3'

services:
  configurator:
    image: oharastream/configurator:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: configurator.dockerfile

  manager:
    image: oharastream/manager:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: manager.dockerfile

  stream:
    image: oharastream/stream:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: stream.dockerfile

  shabondi:
    image: oharastream/shabondi:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: shabondi.dockerfile

  backend:
    image: oharastream/backend:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: backend.dockerfile

  zookeeper:
    image: oharastream/zookeeper:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: zookeeper.dockerfile

  broker:
    image: oharastream/broker:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: broker.dockerfile

  worker:
    image: oharastream/connect-worker:${TAG:-0.13.0-SNAPSHOT}
    build:
      context: .
      dockerfile: worker.dockerfile
